version: '3'
services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    depends_on:
      - ollama

  frontend:
    image: python:3.11-slim
    working_dir: /frontend
    volumes:
      - ./frontend:/frontend
    command: bash -c "pip install -r requirements.txt && streamlit run streamlit_app.py --server.port=8501"
    ports:
      - "8501:8501"

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"

